apiVersion: v1
kind: ConfigMap

metadata:
  name: web-content
  namespace: devsecops

data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>DevSecOps Kubernetes Project</title>

      <style>
        body {
          margin: 0;
          font-family: Arial, sans-serif;
          background: #f4f7fb;
          color: #1f2937;
          text-align: center;
        }

        header {
          background: #111827;
          color: white;
          padding: 30px;
        }

        main {
          max-width: 800px;
          margin: 50px auto;
          padding: 40px;
          background: white;
          border-radius: 15px;
        }

        .status {
          display: inline-block;
          padding: 10px 20px;
          border-radius: 20px;
          background: #dcfce7;
          color: #166534;
          font-weight: bold;
        }
      </style>
    </head>

    <body>

      <header>
        <h1>DevSecOps Kubernetes Final Project</h1>
        <p>Phase 7 — Kubernetes + Helm</p>
      </header>

      <main>
        <h2>Application is Running 🚀 Developed By-MD.AL-AMIN</h2>

        <p>
          This application is running inside a Kubernetes cluster.
        </p>

        <div class="status">
          Kubernetes Deployment: Healthy
        </div>

        <p>
          Deployment → Service → Ingress → Pod
        </p>

        <p>
          Managed with Helm
        </p>
      </main>

    </body>
    </html>